/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2026-04-26 16:15:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.social.Comment;

public final class comments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.social.Comment");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>S C O P E // Social Filter</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Rajdhani:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"particles-js\"></div>\n");
      out.write("    \n");
      out.write("    <div class=\"layout-wrapper\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <h2 class=\"glitch\" data-text=\"Comments Section\">Comments Section</h2>\n");
      out.write("\n");
      out.write("            ");
 String error = (String) request.getAttribute("error");
               if (error != null) { 
      out.write("\n");
      out.write("                <div class=\"error\">[ERROR] ");
      out.print( error );
      out.write("</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"comments\" method=\"post\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"username\">Username</label>\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter username...\" autocomplete=\"off\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"commentText\">Comment</label>\n");
      out.write("                    <input type=\"text\" id=\"commentText\" name=\"commentText\" placeholder=\"Write a comment...\" autocomplete=\"off\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"likes\">Likes</label>\n");
      out.write("                    <input type=\"number\" id=\"likes\" name=\"likes\" value=\"0\" min=\"0\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                ");
 boolean isViewing = (request.getAttribute("comments") != null); 
      out.write("\n");
      out.write("                <input type=\"hidden\" name=\"viewing\" value=\"");
      out.print( isViewing );
      out.write("\">\n");
      out.write("                <div class=\"btn-group\">\n");
      out.write("                    <button type=\"submit\" class=\"btn\">Add Comment</button>\n");
      out.write("                    ");
 if (isViewing) { 
      out.write("\n");
      out.write("                        <a href=\"comments\" class=\"btn btn-secondary\">Hide Comments</a>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <a href=\"viewComments\" class=\"btn btn-secondary\">View Comments</a>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    <a href=\"sortComments\" class=\"btn\">Sort Comments</a>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div class=\"comments\">\n");
      out.write("                <h3>Comments</h3>\n");
      out.write("                ");
 
                   ArrayList<Comment> comments = (ArrayList<Comment>) request.getAttribute("comments");
                   if (comments != null && !comments.isEmpty()) {
                       for (Comment c : comments) {
                
      out.write("\n");
      out.write("                    <div class=\"comment\">\n");
      out.write("                        <div class=\"comment-header\">\n");
      out.write("                            <span class=\"comment-user\">");
      out.print( c.getUserName() );
      out.write("</span>\n");
      out.write("                            <span class=\"comment-likes\">");
      out.print( c.getLikes() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"comment-body\">\n");
      out.write("                            ");
      out.print( c.getFormattedComment() );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 
                       }
                   } else {
                
      out.write("\n");
      out.write("                    <div class=\"empty-state\">\n");
      out.write("                        Click View Comments to see comments.\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        particlesJS('particles-js', {\n");
      out.write("            \"particles\": {\n");
      out.write("                \"number\": { \"value\": 80, \"density\": { \"enable\": true, \"value_area\": 800 } },\n");
      out.write("                \"color\": { \"value\": [\"#05D9E8\", \"#FF2A6D\", \"#ffffff\"] },\n");
      out.write("                \"shape\": { \"type\": \"circle\" },\n");
      out.write("                \"opacity\": { \"value\": 0.5, \"random\": true, \"anim\": { \"enable\": true, \"speed\": 1, \"opacity_min\": 0.1, \"sync\": false } },\n");
      out.write("                \"size\": { \"value\": 3, \"random\": true, \"anim\": { \"enable\": true, \"speed\": 2, \"size_min\": 0.1, \"sync\": false } },\n");
      out.write("                \"line_linked\": { \"enable\": true, \"distance\": 150, \"color\": \"#05D9E8\", \"opacity\": 0.2, \"width\": 1 },\n");
      out.write("                \"move\": { \"enable\": true, \"speed\": 1, \"direction\": \"none\", \"random\": true, \"straight\": false, \"out_mode\": \"out\", \"bounce\": false }\n");
      out.write("            },\n");
      out.write("            \"interactivity\": {\n");
      out.write("                \"detect_on\": \"canvas\",\n");
      out.write("                \"events\": { \"onhover\": { \"enable\": true, \"mode\": \"grab\" }, \"onclick\": { \"enable\": true, \"mode\": \"push\" }, \"resize\": true },\n");
      out.write("                \"modes\": { \"grab\": { \"distance\": 140, \"line_linked\": { \"opacity\": 0.5 } }, \"push\": { \"particles_nb\": 4 } }\n");
      out.write("            },\n");
      out.write("            \"retina_detect\": true\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
