/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2026-04-21 06:17:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>S C O P E // Authenticate</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Rajdhani:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --bg-color: #050505;\n");
      out.write("            --surface-color: #111111;\n");
      out.write("            --text-main: #ffffff;\n");
      out.write("            --text-muted: #888888;\n");
      out.write("            --accent: #ffffff;\n");
      out.write("            --border: #333333;\n");
      out.write("            --glow: rgba(255, 255, 255, 0.15);\n");
      out.write("        }\n");
      out.write("        body { \n");
      out.write("            font-family: 'Rajdhani', sans-serif; \n");
      out.write("            margin: 0; \n");
      out.write("            padding: 0;\n");
      out.write("            background-color: var(--bg-color);\n");
      out.write("            color: var(--text-main);\n");
      out.write("            background-image: \n");
      out.write("                radial-gradient(circle at 50% 0%, #1a1a1a 0%, transparent 50%),\n");
      out.write("                linear-gradient(0deg, rgba(0,0,0,0.8) 0%, transparent 100%);\n");
      out.write("            height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .container { \n");
      out.write("            width: 90%; \n");
      out.write("            max-width: 450px;\n");
      out.write("            margin: auto; \n");
      out.write("            background: rgba(10, 10, 10, 0.6);\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            padding: 40px;\n");
      out.write("            box-shadow: 0 0 40px rgba(0, 0, 0, 0.5), inset 0 0 20px var(--glow);\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .container::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0; left: 0; right: 0; height: 1px;\n");
      out.write("            background: linear-gradient(90deg, transparent, var(--accent), transparent);\n");
      out.write("            opacity: 0.5;\n");
      out.write("        }\n");
      out.write("        h2 { \n");
      out.write("            font-family: 'Orbitron', sans-serif;\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            letter-spacing: 4px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("            color: var(--text-main);\n");
      out.write("            text-shadow: 0 0 10px rgba(255,255,255,0.3);\n");
      out.write("        }\n");
      out.write("        .form-group { \n");
      out.write("            margin-bottom: 25px; \n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        label { \n");
      out.write("            display: block; \n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            color: var(--text-muted);\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("        }\n");
      out.write("        input[type=\"text\"], input[type=\"password\"] { \n");
      out.write("            width: 100%; \n");
      out.write("            padding: 12px 15px; \n");
      out.write("            background: rgba(0, 0, 0, 0.5);\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            color: var(--text-main);\n");
      out.write("            font-family: 'Rajdhani', sans-serif;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("        input[type=\"text\"]:focus, input[type=\"password\"]:focus {\n");
      out.write("            border-color: var(--accent);\n");
      out.write("            box-shadow: 0 0 15px var(--glow);\n");
      out.write("            background: rgba(20, 20, 20, 0.8);\n");
      out.write("        }\n");
      out.write("        .btn { \n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px 20px; \n");
      out.write("            cursor: pointer; \n");
      out.write("            font-family: 'Orbitron', sans-serif;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            letter-spacing: 2px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            background: transparent;\n");
      out.write("            color: var(--text-main);\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            text-align: center;\n");
      out.write("            text-decoration: none;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-top: 15px;\n");
      out.write("        }\n");
      out.write("        .btn::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0; left: -100%; width: 100%; height: 100%;\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent);\n");
      out.write("            transition: all 0.4s ease;\n");
      out.write("        }\n");
      out.write("        .btn:hover::before {\n");
      out.write("            left: 100%;\n");
      out.write("        }\n");
      out.write("        .btn:hover {\n");
      out.write("            background: var(--text-main);\n");
      out.write("            color: var(--bg-color);\n");
      out.write("            box-shadow: 0 0 20px rgba(255,255,255,0.4);\n");
      out.write("            border-color: var(--text-main);\n");
      out.write("        }\n");
      out.write("        .error { \n");
      out.write("            background: rgba(255, 0, 0, 0.1);\n");
      out.write("            border-left: 3px solid #ff3333;\n");
      out.write("            color: #ff3333; \n");
      out.write("            padding: 10px 15px;\n");
      out.write("            margin-bottom: 25px; \n");
      out.write("            font-family: monospace;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .success { \n");
      out.write("            background: rgba(0, 255, 0, 0.1);\n");
      out.write("            border-left: 3px solid #33ff33;\n");
      out.write("            color: #33ff33; \n");
      out.write("            padding: 10px 15px;\n");
      out.write("            margin-bottom: 25px; \n");
      out.write("            font-family: monospace;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .links {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("        .links a {\n");
      out.write("            color: var(--text-muted);\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .links a:hover {\n");
      out.write("            color: var(--accent);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>Authentication</h2>\n");
      out.write("        \n");
      out.write("        ");
 String error = (String) request.getAttribute("error");
           if (error != null) { 
      out.write("\n");
      out.write("            <div class=\"error\">[ERROR] ");
      out.print( error );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        ");
 String success = (String) request.getAttribute("success");
           if (success != null) { 
      out.write("\n");
      out.write("            <div class=\"success\">[SYS] ");
      out.print( success );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"login\" method=\"post\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"username\">Operator ID</label>\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter ID...\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"password\">Passcode</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter passcode...\" required>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn\">Verify</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"links\">\n");
      out.write("            <a href=\"signup\">New Operator? Initialize Registration.</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
